import type { Metadata } from "next";
import "./globals.css";
import Background from "./components/Background";
import theme from "./theme/DefaultTheme";
import { ThemeProvider } from "@mui/material/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <ThemeProvider theme={theme}>
            <Background/>
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
